### PR TITLE
Move from Travis CI to Github Actions.

### PR DESCRIPTION
**Pull request by greschd**
The workflows defined in `.github/workflows` are auto-generated from `.github/workflows_source`. This has the advantage that YAML anchors can be used, reducing duplicate boilerplate.

The `utils/interpolate_yaml_anchors.py` is vendored (from a third party) to do this generating.

Because the previous version of `prospector` failed with our updated dependencies, it was updated. This in turn updated `pylint`, which required some changes to which messages are ignored.

### CODE REVIEW

**Comment by greschd** [comment]
Not sure why the PR doesn't trigger the checks (maybe because `develop` is still on Travis?), they can be found on my branch: https://github.com/greschd/aiida-wannier90/actions

I could make an intermediate PR where both Travis and GHA run if that's desired, but I don't really see any upside from that; we anyway need to check manually that the new CI tests what we want it to.

**Comment by giovannipizzi** [comment]
Thanks! No problem for the tests not running, indeed as you say the travis ones are required but are not running anymore in the branch. That's ok, after merging I'll swap the required tests on develop from travis to GHA.

However, just one thing I would ask: can you add another precommit test that runs the interpolator, and checks that the yams in `workflows` are not changed by this interpolation process? 
The goal for me is to ensure that devs did not change the yml directly - I'm sure I will forget for instance :-)

**Comment by greschd** [comment]
> However, just one thing I would ask: can you add another precommit test that runs the interpolator, and checks that the yams in `workflows` are not changed by this interpolation process?

That's already covered in the `interpolate-workflows`: It triggers whenever either the interpolation script or anything inside `.github` is changed, which includes the "interpolated" workflows. Because they are committed (they need to be, otherwise Github wouldn't pick them up), if they are changed manually the pre-commit hook will revert them and complain.

> I'm sure I will forget for instance :-)

Same here 😂

**Comment by greschd** [comment]
The added complexity from the workflow interpolation is a bit of a tradeoff, but I'm still holding out hope that eventually GHA will support it (feature request [here](https://github.community/t/support-for-yaml-anchors/16128)) and we can drop the pre-commit hook.

**Comment by giovannipizzi** [comment]
ok! merged and switched required tests on develop (feel free to fix is what I did is not correct - I should have put all GHA tests unless I made a mistake).
We'll need to change this also for the master branch when we make a release (or can we do it already now?)

**Comment by giovannipizzi** [comment]
Actually, I just changed also for master - this should be correct as the next merge will have already the new tests. Might be good to check that it's all correct at the next PR

**Comment by greschd** [comment]
> this should be correct as the next merge will have already the new tests

Yeah, I'm not sure about this because the "pull request" part of the actions didn't trigger on this PR. Maybe they go by what's on the current `HEAD` of the branch you're trying to merge onto. But anyway, I think it's ok to switch the required tests. The Travis tests aren't going to run anyway. Worst case we have to "manually" check that the tests ran on the branch we are merging.

**Pull request merged**
