### PR TITLE
Some fixes to make aiida-wannier90 compatible with the latest (develop) aiida-core.

### PR DESCRIPTION
**Pull request by greschd**

### CODE REVIEW

**Comment by greschd** [comment]
This can probably be closed, since AiiDA has moved on a lot since then -- not sure how much of these changes is still relevant.

**Comment by giovannipizzi** [comment]
@greschd Can the branch `workflows` be deleted, losing the unmerged commits? Also, I would suggest to start using forks for work to simplify the contribution workflow by multiple users, and use branches here only for shared developments

**Comment by giovannipizzi** [comment]
Actually, same question for the `workflows_py3` branch

**Comment by greschd** [comment]
Yeah, I deleted these branches, and agree on the forking.

**Pull request closed without merging**
